apiVersion: v1
kind: Service
metadata:
  name: webgo-svc
  labels:
    app: webgo-demo
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8888
    protocol: TCP
  selector:
    app: webgo-demo
